
services:
    apache:
        image: httpd:alpine
        container_name: 'Apache'
        ports:
            - "2005:80"
        volumes:
            - ./htdocs:/usr/local/apache2/htdocs
        networks:
            - padrao
networks:
    padrao:
        driver: bridge